### ISSUE TITLE
GriefPrevention dependency

### ISSUE THREAD

**Issue by FiveEYZ** [Mr-Krab/DupeFixer#1]
Is it possible to have GriefPrevention as a soft dependency?

I manly want to use the "shift+click in (some) container" fix, but its crashing on startup because i dont have GriefPrevention installed (using another protection system).

https://gist.github.com/FiveEYZ/9e68c3d27aadbc694cf322563ad86343

**Comment by Zaxar163** [comment]
Костылём. Сделать IPrivatesPlugin и имплектацию его под каждый из плагинов отдельно.

**Comment by SawFowl** [comment]
Сделаю. Есть мысля как запилить и там не совсем костыль.

**Comment by SawFowl** [comment]
@FiveEYZ 
Neeed test https://github.com/Mr-Krab/DupeFixer/tree/dev
Error at startup eliminated.
Add support RedProtect(barely made it)

**Comment by FiveEYZ** [comment]
nice now it starts up and generates a config :) now i can get to test it :)

**Comment by SawFowl** [comment]
@FiveEYZ If you use RedProtect, then please check the stability of the plugin. The RedProtect developer ignored the Sponge documentation and this creates big problems when you try to get its API.
@Zaxar163 Ты вот посмотри какие костыли мне там пришлось делать. У меня так пригорело с этого RedProtect, уууу блин... +100500 NullPointExeption из-за того, что его автор игнорирует документацию и пишет как на Bukkit API.

**Comment by SawFowl** [comment]
Fixed.
