### ISSUE TITLE
Дюп с порталом в нижний мир

### ISSUE THREAD

**Issue by mistek131995** [Mr-Krab/DupeFixer#6]
Суть дюпа проста... Бросаем предмет в портал, ждем пока он исчезнет и заходим следом. Срабатывает практически с первого раза. Работает на последнем рекомендованном билде губки.

**Comment by SawFowl** [comment]
Попробуй последний релиз. Я написал нужный код, но сам не тестировал еще.

**Comment by mistek131995** [comment]
> Попробуй последний релиз. Я написал нужный код, но сам не тестировал еще.

Блоки больше не перемещаются, спасибо!

**Comment by SawFowl** [comment]
Функционал добавлен.
